import {automaticScan,rectify,detectLayout,readLayout,validLayout} from './auto.js';
import {AREAS,LETTERS,KEY,correctKey,score,bubble,projective,scan,makePdf} from './core.js';
const $=id=>document.getElementById(id), STORE='confere-v1';
let state={version:1,students:[],records:{},templates:{}}, draft=null, photo=null, points=[], stream=null, dirty=false, layout=null, busy=false;
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
function studentsValid(rows){return Array.isArray(rows)&&rows.length>0&&rows.length<2000&&rows.every(s=>s&&typeof s.id==='string'&&/^[\w-]{1,60}$/.test(s.id)&&!['__proto__','constructor','prototype'].includes(s.id)&&typeof s.name==='string'&&s.name.length>0&&s.name.length<180&&typeof s.class==='string'&&/^9º [A-Z]$/.test(s.class))&&new Set(rows.map(s=>s.id)).size===rows.length;}
function validateState(s){if(s.version!==1||!studentsValid(s.students)||!s.records||typeof s.records!=='object'||Array.isArray(s.records))throw Error('Cópia de segurança inválida.');const ids=new Set(s.students.map(x=>x.id));for(const [id,r] of Object.entries(s.records)){if(!ids.has(id)||!['en','es'].includes(r.lang)||!r.days||typeof r.days!=='object')throw Error('Registro inválido.');for(const [d,v] of Object.entries(r.days)){if(!['0','1'].includes(d)||!v||!Array.isArray(v.answers)||v.answers.length!==90||v.answers.some(a=>!['','X',...'ABCDE'].includes(a))||typeof v.savedAt!=='string')throw Error('Respostas inválidas.');}}if(s.templates)for(const [d,l] of Object.entries(s.templates))if(!['0','1'].includes(d)||!validLayout(l))throw Error('Modelo inválido na cópia.');return s;}
try{const raw=localStorage.getItem(STORE);if(raw)state=validateState(JSON.parse(raw));}catch(e){notice('Não foi possível carregar os dados salvos. Restaure uma cópia de segurança na aba Preparar.',true);}
function persist(next){try{localStorage.setItem(STORE,JSON.stringify(next));state=next;return true;}catch(e){notice('Não foi possível salvar neste navegador. Seus dados atuais continuam abertos: baixe uma cópia de segurança. Verifique o espaço e as permissões de armazenamento.',true);return false;}}
function selected(){return state.students.find(s=>s.id===$('studentSelect').value);}
function record(){return state.records[selected()?.id];}
function hasWork(){return dirty||!!photo||!!stream;}
function templateStatus(){const ts=state.templates||{};$('templateStatus').textContent=[0,1].map(d=>`${d+1}º dia: ${ts[d]?'modelo personalizado de 90 questões':'modelo oficial de 90 questões pronto'}`).join(' · ');}
function clearWork(){draft=null;photo=null;points=[];layout=null;dirty=false;stopCamera();$('review').hidden=true;$('alignment').hidden=true;$('captureStart').hidden=false;$('photo').value='';$('photoCanvas').width=1;$('photoCanvas').height=1;$('reviewConfirmed').checked=false;$('saveDay').disabled=true;$('saveDay').hidden=false;}
function leaveWork(){if(busy){notice('Aguarde a leitura terminar.',true);return false;}if(hasWork()&&!confirm('Descartar a foto e as respostas ainda não salvas?'))return false;clearWork();return true;}
function fillClasses(){const classes=[...new Set(state.students.map(s=>s.class))].sort();$('classSelect').innerHTML=classes.map(c=>`<option>${safe(c)}</option>`).join('');$('reportClass').innerHTML='<option value="">Todas as turmas</option>'+classes.map(c=>`<option>${safe(c)}</option>`).join('');fillStudents();$('rosterCount').textContent=`${state.students.length} estudantes importados · ${classes.length} turmas`;$('noStudents').hidden=state.students.length>0;}
function fillStudents(){const rows=state.students.filter(s=>s.class===$('classSelect').value);$('studentSelect').innerHTML=rows.map(s=>`<option value="${safe(s.id)}">${safe(s.name)}</option>`).join('');loadStudent();}
function loadStudent(){$('language').value=record()?.lang||'';updateSummary();}
function updateSummary(){const r=record();$('studentSummary').innerHTML=[0,1].map(d=>`<div>${d+1}º dia <strong>${r?.days?.[d]?'✓ salvo':'· ainda não lido'}</strong></div>`).join('');if(r){const sc=score(r);$('studentSummary').innerHTML+=`<div><b>${sc.total} acertos</b> em ${sc.read} questões lidas</div>`;}$('progress').textContent=Object.values(state.records).filter(r=>r.days[0]&&r.days[1]).length;}
let previousClass='',previousStudent='',previousDay='0';
function remember(){previousClass=$('classSelect').value;previousStudent=$('studentSelect').value;previousDay=$('day').value;}
$('classSelect').onchange=()=>{if(!leaveWork()){$('classSelect').value=previousClass;return;}fillStudents();remember();};
$('studentSelect').onchange=()=>{if(!leaveWork()){$('studentSelect').value=previousStudent;return;}loadStudent();remember();};
$('day').onchange=()=>{if(!leaveWork()){$('day').value=previousDay;return;}remember();};
$('language').onchange=()=>{const r=record();if(r&&r.lang!==$('language').value){if(!$('language').value){$('language').value=r.lang;return;}if(!confirm('Alterar o idioma e recalcular as questões 1 a 5 deste estudante?')){$('language').value=r.lang;return;}const next=structuredClone(state);next.records[selected().id].lang=$('language').value;if(!persist(next))$('language').value=r.lang;updateSummary();renderReport();}};
function ready(){if(busy){notice('Aguarde a leitura terminar.',true);return false;}if(!selected()){notice('Importe a lista de estudantes na aba Preparar.',true);return false;}if(!$('language').value){notice('Selecione inglês ou espanhol para este estudante.',true);$('language').focus();return false;}return true;}
function tab(name){document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='report')renderReport();if(name!=='read')stopCamera();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('rosterFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.version!==1||!studentsValid(data.students))throw Error('Use o arquivo de estudantes fornecido com o sistema.');if(!leaveWork())return;const ids=new Set(data.students.map(s=>s.id));if(Object.keys(state.records).some(id=>!ids.has(id)))throw Error('Essa lista removeria estudantes com resultados. Baixe uma cópia de segurança antes de trocar de lista.');const next={...state,students:data.students.map(({id,name,class:cls})=>({id,name,class:cls}))};if(!persist(next))return;fillClasses();remember();notice(`${state.students.length} estudantes importados. Você já pode iniciar a correção.`);tab('read');}catch(err){notice(err.message,true);}finally{e.target.value='';}};
$('restoreFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const s=validateState(JSON.parse(await file.text()));if(!confirm('Restaurar esta cópia e substituir os dados atuais deste navegador?'))return;clearWork();if(!persist(s))return;fillClasses();remember();templateStatus();notice('Cópia restaurada.');}catch(err){notice('Falha ao restaurar: '+err.message,true);}finally{e.target.value='';}};
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('cameraView').hidden=true;}
$('cameraBtn').onclick=async()=>{if(!ready())return;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('A câmera precisa de HTTPS. Use “Fotografar ou escolher imagem” ou abra o site no GitHub Pages.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:2400},height:{ideal:1800}},audio:false});$('video').srcObject=stream;$('cameraView').hidden=false;$('captureStart').hidden=true;}catch(e){notice(e.name==='NotAllowedError'?'Acesso à câmera não autorizado. Permita o acesso nas configurações ou use o botão para escolher uma imagem.':e.message,true);}};
$('closeCamera').onclick=()=>{stopCamera();$('captureStart').hidden=false;};
function setPhoto(source){const c=document.createElement('canvas');const w=source.videoWidth||source.naturalWidth||source.width,h=source.videoHeight||source.naturalHeight||source.height;if(!w||!h)throw Error('A imagem ainda não está pronta. Tente novamente.');const scale=Math.min(1,2400/Math.max(w,h));c.width=Math.round(w*scale);c.height=Math.round(h*scale);c.getContext('2d').drawImage(source,0,0,c.width,c.height);clearWork();photo=c;points=[];$('alignment').hidden=false;$('captureStart').hidden=true;$('zoom').value=1;$('photoCanvas').style.width='100%';drawPhoto();setTimeout(runAutomatic,30);}
$('takePhoto').onclick=()=>{try{setPhoto($('video'));}catch(e){notice(e.message,true);}};
$('photo').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!ready()){e.target.value='';return;}if(hasWork()&&!confirm('Substituir a leitura ainda não salva?')){e.target.value='';return;}const url=URL.createObjectURL(f);try{const img=new Image();img.src=url;await img.decode();setPhoto(img);}catch(err){notice('Não foi possível abrir a foto. Tente uma imagem JPG, PNG ou WebP.',true);}finally{URL.revokeObjectURL(url);e.target.value='';}};
function drawPhoto(){if(!photo)return;const c=$('photoCanvas');c.width=photo.width;c.height=photo.height;const ctx=c.getContext('2d');ctx.drawImage(photo,0,0);if(draft&&layout)layout.rows.forEach((r,q)=>{for(let o=0;o<5;o++){ctx.beginPath();ctx.arc(r.x+o*r.step,r.y,r.radius*.85,0,Math.PI*2);ctx.strokeStyle=draft[q].answer===LETTERS[o]?'#00a33f':'#147dff88';ctx.lineWidth=2;ctx.stroke();}});$('alignHelp').textContent=layout?`${layout.count} questões localizadas automaticamente. Confira as respostas abaixo.`:'A leitura começa automaticamente. Inclua os quatro cantos e mantenha os três quadrados no alto à esquerda.';}
async function runAutomatic(){if(!photo||busy)return;busy=true;$('analyze').disabled=true;notice('Localizando os marcadores e lendo as bolinhas…');await new Promise(r=>setTimeout(r,30));try{const im=photo.getContext('2d').getImageData(0,0,photo.width,photo.height),result=automaticScan(im,state.templates?.[$('day').value]||null);layout=result.layout;draft=result.answers;dirty=true;const c=document.createElement('canvas');c.width=result.normalized.width;c.height=result.normalized.height;c.getContext('2d').putImageData(new ImageData(result.normalized.data,c.width,c.height),0,0);photo=c;drawPhoto();renderReview();notice(layout.count===90?'90 respostas localizadas. Confira as marcações e salve.':'Modelo de teste: 40 questões reconhecidas. A visualização não será salva nem pontuada como uma prova de 90.');$('review').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){draft=null;layout=null;$('review').hidden=true;notice(e.message,true);}finally{busy=false;$('analyze').disabled=false;}}
$('zoom').oninput=e=>$('photoCanvas').style.width=`${Number(e.target.value)*100}%`;
$('rotatePhoto').onclick=()=>{if(!photo||busy)return;const c=document.createElement('canvas');c.width=photo.height;c.height=photo.width;const ctx=c.getContext('2d');ctx.translate(c.width,0);ctx.rotate(Math.PI/2);ctx.drawImage(photo,0,0);photo=c;points=[];layout=null;draft=null;dirty=false;$('review').hidden=true;drawPhoto();runAutomatic();};
$('discard').onclick=()=>{if(!busy)leaveWork();};
$('analyze').onclick=runAutomatic;
$('manualBtn').onclick=()=>{if(!ready())return;if(!leaveWork())return;const existing=record()?.days?.[$('day').value];draft=Array.from({length:90},(_,i)=>({answer:existing?.answers[i]||'',status:'Conferir'}));dirty=true;renderReview();$('review').scrollIntoView({behavior:'smooth'});};
function renderReview(){if(!draft)return;$('review').hidden=false;$('reviewConfirmed').checked=false;$('saveDay').disabled=true;const d=draft.length===40?0:Number($('day').value),count=draft.filter(r=>r.status!=='Lida'&&r.status!=='Conferida').length;$('reviewTitle').textContent=`${selected().name} · ${draft.length===40?'Teste de 40 questões':(d+1)+'º dia'}`;$('reviewConfirmed').parentElement.hidden=draft.length!==90;$('saveDay').hidden=draft.length!==90;$('reviewStats').textContent=`${count} para conferir`;$('answerGrid').innerHTML=draft.map((r,i)=>{const flagged=!['Lida','Conferida'].includes(r.status);if($('onlyFlagged').checked&&!flagged)return '';return `<div class="answer ${flagged?'flagged':''}"><strong>${i+1+d*90}</strong><select aria-label="Resposta da questão ${i+1+d*90}" data-index="${i}">${['',...LETTERS,'X'].map(a=>`<option value="${a}" ${a===r.answer?'selected':''}>${a===''?'Branco':a==='X'?'Dupla':a}</option>`).join('')}</select><small>${r.status}</small></div>`;}).join('');$('answerGrid').querySelectorAll('select').forEach(sel=>sel.onchange=()=>{draft[Number(sel.dataset.index)]={answer:sel.value,status:'Conferida'};renderReview();if(photo)drawPhoto();});}
$('onlyFlagged').onchange=renderReview;
$('reviewConfirmed').onchange=()=>{$('saveDay').disabled=!$('reviewConfirmed').checked;};
$('saveDay').onclick=()=>{if(!draft||draft.length!==90||!ready()||!$('reviewConfirmed').checked)return;const s=selected(),d=$('day').value;if(record()?.days?.[d]&&!confirm('Substituir a correção já salva deste cartão?'))return;const next=structuredClone(state),r=next.records[s.id]||{lang:$('language').value,days:{}};r.lang=$('language').value;r.days[d]={answers:draft.map(x=>x.answer),savedAt:new Date().toISOString()};next.records[s.id]=r;if(!persist(next))return;clearWork();updateSummary();renderReport();notice(`${s.name}: ${Number(d)+1}º dia salvo. ${r.days[0]&&r.days[1]?'Os dois cartões estão concluídos.':'Falta o outro cartão.'}`);};
function filtered(){return state.students.filter(s=>!$('reportClass').value||s.class===$('reportClass').value);}
function status(r){return !r?'Não iniciado':r.days[0]&&r.days[1]?'Completo':r.days[0]?'Só 1º dia':'Só 2º dia';}
function renderReport(){const rows=filtered(),complete=rows.filter(s=>state.records[s.id]?.days[0]&&state.records[s.id]?.days[1]).length,started=rows.filter(s=>state.records[s.id]).length;$('reportCards').innerHTML=`<div><b>${complete}/${rows.length}</b><span>concluídos</span></div><div><b>${started-complete}</b><span>parciais</span></div><div><b>${rows.length-started}</b><span>não iniciados</span></div>`;$('reportBody').innerHTML=rows.map(s=>{const r=state.records[s.id],sc=score(r||{days:{}});return `<tr><td>${safe(s.name)}<small>${safe(s.class)} · ${r?(r.lang==='es'?'Espanhol':'Inglês'):'Idioma pendente'}</small></td><td><button data-student="${safe(s.id)}">${status(r)}</button></td>${sc.areas.map(a=>`<td>${a.read?a.correct+'/45':'—'}</td>`).join('')}<td>${sc.read?`${sc.total}/${sc.read}`:'—'}</td></tr>`;}).join('');$('reportBody').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!leaveWork())return;const s=state.students.find(s=>s.id===b.dataset.student);$('classSelect').value=s.class;fillStudents();$('studentSelect').value=s.id;loadStudent();remember();tab('read');});$('downloadPdf').disabled=!rows.length;}
$('reportClass').onchange=renderReport;
function download(data,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('backup').onclick=()=>download(JSON.stringify(state,null,2),'confere-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');
$('downloadPdf').onclick=()=>{const rows=filtered();if(!rows.length)return;const lines=['CONFERE | RELATORIO DO SIMULADO - 9º ANO',`Emitido em: ${new Date().toLocaleString('pt-BR')}`,`Turma: ${$('reportClass').value||'Todas'} | Estudantes: ${rows.length}`,'','L = Linguagens; H = Humanas; N = Natureza; M = Matematica.','Cada area tem 45 questoes. Total completo: 180 questoes.','-- = cartao ainda nao lido. Branco e dupla contam como erro.','Acertos brutos; nao representa nota TRI.',''];for(const s of rows){const r=state.records[s.id],sc=score(r||{days:{}});if(lines.length%48>41)while(lines.length%48)lines.push('');const wrapped=s.name.match(/.{1,82}(?:\s|$)|.{1,82}/g)||[s.name];lines.push(...wrapped.map(l=>l.trim()),`${s.class} | ${status(r)} | Idioma: ${r?(r.lang==='es'?'Espanhol':'Ingles'):'pendente'}`);lines.push(sc.areas.map((a,i)=>`${'LHNM'[i]}: ${a.read?String(a.correct).padStart(2,' ')+'/45':'--   '}`).join('   ')+`   TOTAL: ${sc.read?sc.total+'/'+sc.read:'--'}`);if(r){const blanks=Object.values(r.days).flatMap(d=>d.answers).filter(a=>a==='').length,doubles=Object.values(r.days).flatMap(d=>d.answers).filter(a=>a==='X').length;lines.push(`Em branco: ${blanks} | Duplas: ${doubles} | ${sc.read<180?'PARCIAL':'CONCLUIDO'}`);}else lines.push('Aguardando leitura dos dois cartoes.');lines.push('--------------------------------------------------------------------------','');}download(makePdf(lines),'relatorio-simulado-9ano.pdf','application/pdf');notice('Relatório PDF gerado. Confira o arquivo nos downloads do navegador.');};
function renderKey(){const k=correctKey($('keyLanguage').value);$('keyView').innerHTML=AREAS.map((a,i)=>`<div class="key-area"><h3>${a} · ${i*45+1} a ${(i+1)*45}</h3><div class="key-grid">${k.slice(i*45,(i+1)*45).map((v,j)=>`<span>${i*45+j+1} <b>${v}</b></span>`).join('')}</div></div>`).join('');}
$('keyLanguage').onchange=renderKey;
window.addEventListener('beforeunload',e=>{if(hasWork()){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream){stopCamera();$('captureStart').hidden=false;}});
fillClasses();remember();renderReport();renderKey();templateStatus();

$('templateFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(busy){notice('Aguarde a leitura terminar.',true);return;}const target=$('templateDay').value;let url;try{notice('Identificando a grade do cartão em branco…');url=URL.createObjectURL(f);const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,2400/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const normalized=rectify(c.getContext('2d').getImageData(0,0,c.width,c.height));const l=detectLayout(normalized);if(l.count!==90)throw Error(`Este modelo tem ${l.count} questões. O cadastro para correção exige o cartão completo de 90. Você pode usar esta imagem para testar a leitura na aba Corrigir cartão.`);const answers=readLayout(normalized,l);if(answers.some(a=>a.answer!==''))throw Error('O modelo precisa estar com todas as respostas em branco. Use uma imagem sem preenchimentos.');if(!validLayout(l))throw Error('Grade fora do padrão reconhecido.');if(state.templates?.[target]&&!confirm('Substituir o modelo de leitura deste dia?'))return;const next=structuredClone(state);next.templates||={};next.templates[target]=l;if(persist(next)){templateStatus();notice(`Modelo do ${Number(target)+1}º dia cadastrado. As próximas fotos usarão essa grade automaticamente.`);}}catch(err){notice(err.message,true);}finally{if(url)URL.revokeObjectURL(url);e.target.value='';}};

$('useOfficial').onclick=()=>{const d=$('templateDay').value;const next=structuredClone(state);if(next.templates)delete next.templates[d];if(persist(next)){templateStatus();notice(`Modelo oficial ativado para o ${Number(d)+1}º dia. Os resultados salvos foram mantidos.`);}};
