import {test} from 'node:test';import assert from 'node:assert/strict';
import {automaticScan,validLayout} from '../auto.js';
function form(marked=false){const width=1304,height=1848,data=new Uint8ClampedArray(width*height*4).fill(255);function pixel(x,y,r,g,b){const j=(y*width+x)*4;data[j]=r;data[j+1]=g;data[j+2]=b;}for(const [cx,cy] of [[53,53],[120,53],[186,53],[1249,53],[53,1780],[1249,1780]])for(let y=cy-17;y<=cy+17;y++)for(let x=cx-17;x<=cx+17;x++)pixel(x,y,0,0,0);for(let q=0;q<90;q++){const x=127+Math.floor(q/30)*360,y=840+(q%30)*28;for(let o=0;o<5;o++){const cx=x+o*31;for(let yy=y-11;yy<=y+11;yy++)for(let xx=cx-11;xx<=cx+11;xx++){const rr=Math.hypot(xx-cx,yy-y);if(rr>=9.5&&rr<=11)pixel(xx,yy,255,45,90);if(marked&&q>0&&(q===1?[0,3].includes(o):o===q%5)&&rr<8)pixel(xx,yy,10,10,10);}}}return {width,height,data};}
test('grade anônima de 90: descoberta automática, cadastro e respostas',()=>{const blank=automaticScan(form());assert.equal(blank.layout.count,90);assert.ok(validLayout(blank.layout));assert.ok(blank.answers.every(a=>a.answer===''));const result=automaticScan(form(true),blank.layout);assert.deepEqual(result.answers.map(a=>a.answer),Array.from({length:90},(_,q)=>q===0?'':q===1?'X':'ABCDE'[q%5]));});
test('não aprova imagem sem marcadores',()=>{const im=form();im.data.fill(255,0,im.width*130*4);assert.throws(()=>automaticScan(im),/quadrados/);});
test('modelo com posições inválidas é recusado',()=>{assert.equal(validLayout({version:1,width:1304,height:1848,count:90,rows:Array(90).fill({x:1300,y:900,step:31,radius:11})}),false);});
function monochrome(marked=false){const im=form(marked);for(let i=0;i<im.data.length;i+=4){const r=im.data[i],g=im.data[i+1],b=im.data[i+2];if(r===255&&g===45){im.data[i]=im.data[i+1]=im.data[i+2]=125;}else if(marked&&r===10){im.data[i]=40;im.data[i+1]=30;im.data[i+2]=110;}}return im;}
test('impressão cinza: 90 em branco não impedem descobrir a grade',()=>{const r=automaticScan(monochrome());assert.equal(r.layout.count,90);assert.ok(r.answers.every(a=>a.answer===''));});
test('impressão cinza e caneta azul: branco, dupla e respostas',()=>{const r=automaticScan(monochrome(true));assert.deepEqual(r.answers.map(a=>a.answer),Array.from({length:90},(_,q)=>q===0?'':q===1?'X':'ABCDE'[q%5]));});
test('uma bolinha ilegível não elimina a linha inteira da grade',()=>{const im=monochrome();const cx=127+2*31,cy=840+10*28;for(let y=cy-12;y<=cy+12;y++)for(let x=cx-12;x<=cx+12;x++){const i=(y*im.width+x)*4;im.data[i]=im.data[i+1]=im.data[i+2]=255;}const r=automaticScan(im);assert.equal(r.layout.count,90);assert.equal(r.answers[10].answer,'');});
