import {test} from 'node:test';import assert from 'node:assert/strict';
import {KEY,correctKey,score,projective,bubble,classify,scan,makePdf,validateCorners} from '../core.js';
test('180 respostas, idiomas e fronteiras das áreas',()=>{assert.equal(KEY.length,180);assert.ok(KEY.every(a=>'ABCDE'.includes(a)));assert.equal(correctKey('es').slice(0,5).join(''),'CADEA');assert.equal(KEY.slice(0,5).join(''),'DADDB');assert.deepEqual([KEY[44],KEY[45],KEY[89],KEY[90],KEY[134],KEY[135],KEY[179]],['E','B','C','E','D','C','C']);});
test('pontuação completa, parcial, idioma, branco e dupla',()=>{const r={lang:'en',days:{0:{answers:KEY.slice(0,90)},1:{answers:KEY.slice(90)}}};assert.equal(score(r).total,180);assert.deepEqual(score(r).areas.map(a=>a.correct),[45,45,45,45]);r.lang='es';assert.equal(score(r).total,177);r.lang='en';r.days[0].answers[0]='';r.days[0].answers[1]='X';assert.equal(score(r).total,178);delete r.days[1];assert.equal(score(r).read,90);assert.equal(score(r).areas[2].read,0);});
test('perspectiva e ordem dos pontos',()=>{const p=[{x:80,y:90},{x:900,y:60},{x:850,y:460},{x:130,y:430}];assert.ok(validateCorners(p));assert.equal(validateCorners([p[0],p[3],p[2],p[1]]),false);const f=projective(p);[[0,0],[1,0],[1,1],[0,1]].forEach(([u,v],i)=>{assert.ok(Math.abs(f(u,v).x-p[i].x)<1e-7);assert.ok(Math.abs(f(u,v).y-p[i].y)<1e-7);});});
test('marcações duplas e baixa confiança exigem revisão',()=>{assert.equal(classify([.8,.8,0,0,0]).answer,'X');assert.equal(classify([.1,.1,.1,.1,.1]).answer,'');assert.equal(classify([.4,.1,.1,.1,.1]).status,'Conferir');assert.equal(classify([.1,.1,.8,.1,.1]).answer,'C');});
test('90 bolinhas preenchidas em imagem com perspectiva',()=>{const width=1100,height=650,data=new Uint8ClampedArray(width*height*4).fill(255),p=[{x:80,y:90},{x:1000,y:65},{x:950,y:580},{x:120,y:540}],map=projective(p);for(let q=0;q<90;q++){const o=LETTERS.indexOf(KEY[q]),uv=bubble(q,o),pt=map(uv.u,uv.v);for(let y=Math.floor(pt.y-8);y<=pt.y+8;y++)for(let x=Math.floor(pt.x-8);x<=pt.x+8;x++)if((x-pt.x)**2+(y-pt.y)**2<64){let at=(y*width+x)*4;data[at]=data[at+1]=data[at+2]=0;}}assert.deepEqual(scan({data,width,height},p).map(r=>r.answer),KEY.slice(0,90));});
const LETTERS='ABCDE';
test('PDF paginado com cabeçalho válido e WinAnsi',()=>{const pdf=makePdf(Array.from({length:100},(_,i)=>`JOÃO - Questão ${i}`));const s=new TextDecoder('latin1').decode(pdf);assert.ok(s.startsWith('%PDF-1.4'));assert.ok(s.includes('/Count 3'));assert.ok(s.includes('JOÃO'));});
